---
# Source: helm/templates/api-deploy.yaml
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: current-version-api
  namespace: default
  labels:
    version: v4
spec:
  selector:
    matchLabels:
      app: current-version-api
  replicas: 1
  template:
    metadata:
      labels:
        app: current-version-api
        version: v4
    spec:
      containers:
      - name: api
        image: denvasyliev/k8sdiy:build-599e1af
        command:
          - ./app
          - "-role"
          - "api"
          - "-server"
          - nats-cluster
        imagePullPolicy: Always
        env:
          - name: APP_BACKEND
            value: "iscii"
          - name: APP_DATASTORE
            value: "data"
          - name: APP_DB
            value: "root@tcp(db:3306)/demo"
          - name: APP_CACHE
            value: "cache"
          - name: APP_LICENSE
            valueFrom:
              secretKeyRef:
                name: current-version-secret
                key: license
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
      volumes:
        - name: data
          configMap:
            name: current-version-configmap
